- name: check if the project exists
  oc_project:
    state: list
    name: "{{ namespace }}"
  register: project_exists

- name: fail if the project doesn't exist
  assert:
    that:
      - "{{ project_exists.module_results|length>0 }}"
    msg: "The project -{{ namespace }}- must be created first"

- name: make sure the existing project owner matches the inventory information
  assert:
    that:
      - "{{ project_exists.module_results.metadata.annotations['openshift.io/requester'] == admin_user }}"
    msg: "The existing project owner for -{{ namespace }}- is different from the inventory admin user!"

- name: allocate the IP to the namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: NetNamespace
      egressIPs:
        - "{{ private_ip }}"
      metadata:
        name: "{{ namespace }}"
  when: project_exists.module_results|length>0
