---

- name: open port 53 for internal DNS
  lineinfile:
    line: "{{ item }}"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'
  with_items:
    - "-A INPUT -p udp -m udp --dport 53 -j ACCEPT"
    - "-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT"

- name: add a script for pruning old objects
  copy:
    src: files/poc_prune_objects.bash
    dest: /usr/local/bin/poc_prune_objects.bash
    mode: '0755'

- name: add a cron entry for object auto pruning
  cron:
    name: "Prune old OpenShift objects"
    hour: "{{ groups.masters.index(inventory_hostname) }}"
    minute: "42"
    cron_file: poc_openshift_pruning
    user: root
    job: "/usr/local/bin/poc_prune_objects.bash"

- when:
    - deploy_ldap_group_sync | default(False) | bool
  block:
    - name: add a script for syncing ldap groups
      copy:
        src: files/poc_sync_ldap_groups.bash
        dest: /usr/local/bin/poc_sync_ldap_groups.bash
        mode: '0755'

    - name: distribute ldap sync tasks among all masters on different hours of day
      set_fact:
        l_ldap_sync_cron_hours: |
          [{% for hour in range(groups.masters.index(inventory_hostname), 24, groups.masters|length )%}
          {{ hour }},
          {% endfor %}]

    - name: add a cron entry for syncing ldap groups
      cron:
        name: "Sync group information from LDAP"
        hour: "{{ l_ldap_sync_cron_hours|join(',') }}"
        minute: "{{ 59|random(seed=cluster_name) }}"
        cron_file: poc_sync_ldap_groups
        user: root
        job: "/usr/local/bin/poc_sync_ldap_groups.bash --confirm"
  # endblock

- name: add a script for restarting heketi-storage
  copy:
    src: files/poc_restart_heketi.bash
    dest: /usr/local/bin/poc_restart_heketi.bash
    mode: '0755'

- name: distribute heketi restart tasks among all masters on different days of week
  set_fact:
    l_heketi_restart_cron_weekdays: |
      [{% for wd in range(groups.masters.index(inventory_hostname), 7, groups.masters|length )%}
      {{ wd }},
      {% endfor %}]

- name: add a cron entry for restarting heketi-storage
  cron:
    name: "Restart heketi-storage"
    weekday: "{{ l_heketi_restart_cron_weekdays|join(',') }}"
    hour: "02"
    minute: "45"
    cron_file: poc_restart_heketi
    user: root
    job: "/usr/local/bin/poc_restart_heketi.bash"
