---

- name: open port 53 for internal DNS
  lineinfile:
    line: "{{ item }}"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT'
  with_items:
    - "-A INPUT -p udp -m udp --dport 53 -j ACCEPT"
    - "-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT"
