---
- name: ensure /etc/origin/master/login exists
  file:
    state: "directory"
    path: "/etc/origin/master/login"

- name: copy the login page html files
  template:
    src: "{{ item }}"
    dest: "/etc/origin/master/login/{{ item | regex_replace('.j2$','') }}"
  with_items:
    - "login.html.j2"
    - "provider.html.j2"
    - "error.html.j2"

- name: update the login pages configuration in master-config
  yedit:
    src: "{{ openshift_master_config_file }}"
    key: oauthConfig.templates
    value: |
      errorPage: /etc/origin/master/login/error.html
      login: /etc/origin/master/login/login.html
      providerSelection: /etc/origin/master/login/provider.html
  notify:
    - restart master
    - restart master api
