# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

# Define colour macros and utility functions for our custom bash prompt
YELLOW="$(tput setaf 3)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/*\(.*\)/\1/' -e 's/ //g'
}

short_cwd() {
    echo $PWD | sed -e "s|^$HOME|~|g"
}

branch-info() {
    for repo in openshift-ansible openshift-environments poc; do
        branch=$(cd /opt/deployment/$repo && parse_git_branch)
        printf "%23s: %s\n" $repo $branch
    done
}
# All non-printable output should be enclosed in '\[\]' to avoid bash evaluating the prompt length wrong,
# which will in turn cause line wrapping issues
# https://unix.stackexchange.com/questions/105958/terminal-prompt-not-wrapping-correctly
export PS1='\[${YELLOW}\]${ENV_NAME}\[${RESET}\] $(short_cwd) \[${GREEN}\]($(parse_git_branch))\[${RESET}\] > '

source init_env.bash

echo
branch-info
echo
