---
image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  OPENSHIFT_ANSIBLE_REPO_URL: https://github.com/openshift/openshift-ansible.git
  OPENSHIFT_ANSIBLE_VERSION: release-1.5
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

services:
  - docker:dind

before_script:
  - docker version
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - apk update
  - 'which ssh-agent || (apk add openssh-client)'
  - 'which bash || (apk add bash)'
  - 'which git || (apk add git)'
  - mkdir -p ~/.ssh
  - eval "$(ssh-agent -s)"
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo "$CI_RUNNER_SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  - 'stat -t ../openshift-environments || (git clone $ENVIRONMENTS_REPO_URL ../openshift-environments)'
  - '(cd ../openshift-environments; git rev-parse --verify -q remotes/origin/$CI_COMMIT_REF_NAME) &&
     (cd ../openshift-environments; git checkout $CI_COMMIT_REF_NAME; git pull)'
  - '(cd ../openshift-environments; git rev-parse --verify -q remotes/origin/$CI_COMMIT_REF_NAME) ||
     (cd ../openshift-environments; git checkout master; git pull)'
  - 'stat -t ../openshift-ansible || (git clone $OPENSHIFT_ANSIBLE_REPO_URL ../openshift-ansible)'
  - '(cd ../openshift-ansible; git checkout $OPENSHIFT_ANSIBLE_VERSION; git pull)'


stages:
  - docker_build
  - ci_env_deploy
  - cleanup

docker_image_build_job:
  stage: docker_build
  script:
    - cd container-src/poc-deployer
    - docker pull $IMAGE_TAG
    - docker build --pull=true --cache-from $IMAGE_TAG -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy_ci_openshift_job:
  stage: ci_env_deploy
  script:
    - cd scripts
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG cscfi/poc-deployer
    - ./run_deployment_container.bash -e oso-ci-singlemaster -P /dev/shm/secret/vaultpass ./run_playbook.bash site.yml

deprovision_ci_openshift_job:
  stage: cleanup
  script:
    - cd scripts
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG cscfi/poc-deployer
    - ./run_deployment_container.bash -e oso-ci-singlemaster -P /dev/shm/secret/vaultpass ./run_playbook.bash deprovision.yml
  when: always
