{
 "title": "Openshift Cluster Overview",
 "description": "Openshift Cluster Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU Core Count & Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cores Used in Openshift",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_memory_bytes)" }
   ]
  },
  {
   "title": "Cores used by Masters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_master=\"true\"})"
    }
   ]
  },
  {
   "title": "Cores use by Infra Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_infra=\"true\"})"
    }
   ]
  },
  {
   "title": "Cores used by GlusterFS nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_glusterfs=\"true\"})"
    }
   ]
  },
  {
   "title": "Cores used by Compute Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Master Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\"})"
    }
   ]
  },
  {
   "title": "Infra Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\"})"
    }
   ]
  },
  {
   "title": "GlusterFS Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_glusterfs=\"true\"})"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "CPU Request Allocation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"})*1000)) / (sum (machine_cpu_cores)*1000)  * 100 "
    }
   ]
  },
  {
   "title": "CPU Limit Allocation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (container_spec_cpu_quota)/100) / (sum (machine_cpu_cores)*1000)  * 100 "
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Memory Request Allocation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_pod_container_resource_requests_memory_bytes)) / (sum (machine_memory_bytes))  * 100 "
    }
   ]
  },
  {
   "title": "Total Memory Limit Allocation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (container_spec_memory_limit_bytes{pod_name!=\"\"})) / (sum (machine_memory_bytes))  * 100 "
    }
   ]
  },
  {
   "title": "Maximum Number of Pods we can Run on Compute Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})*10\n"
    }
   ]
  },
  {
   "title": "Pod Limit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "1/((sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})*10) / (sum (kube_pod_info{namespace!=\"default\",namespace!=\"openshift-infra\",namespace!=\"openshift-monitoring\",namespace!=\"logging\",created_by_kind!=\"<none>\"})))  * 100 "
    }
   ]
  },
  {
   "title": "Current number of Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_pod_info{namespace!=\"default\",namespace!=\"openshift-infra\",namespace!=\"openshift-monitoring\",namespace!=\"logging\",created_by_kind!=\"<none>\"})"
    }
   ]
  },
  { "title": "Server Vital Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Project Quotas - Memory Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (limit)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"})",
     "legendFormat": "Total Limits"
    },
    {
     "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Project Quotas - CPU Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) by (namespace)",
     "legendFormat": "{{ namespace }} (limit)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"})",
     "legendFormat": "Total Limits"
    },
    {
     "expr": "sum (machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OpenShift local volumes usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{device='/dev/mapper/vg_data-lv_os_local'}  / node_filesystem_size_bytes{device='/dev/mapper/vg_data-lv_os_local'})) * 100",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Server Load over 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total > 0",
     "legendFormat": "{{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Phase across Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU usage (1m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 59 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100"
      }
     ]
    },
    {
     "title": "Master CPU usage (1m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 59 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_master=\"true\"}[1m])) / sum (machine_cpu_cores{node_role_kubernetes_io_master=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Infrastructure CPU usage (1m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 59 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_infra=\"true\"}[1m])) / sum (machine_cpu_cores{node_role_kubernetes_io_infra=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Compute CPU usage (1m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 59 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_compute=\"true\"}[1m])) / sum (machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum (machine_cpu_cores)" }
     ]
    },
    {
     "title": "Total Used Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))"
      }
     ]
    },
    {
     "title": "Total Millicore Limit",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_spec_cpu_quota)/100"
      }
     ]
    },
    {
     "title": "Master Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Used Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_master=\"true\"}[1m]))"
      }
     ]
    },
    {
     "title": "Millicore Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_spec_cpu_quota{node_role_kubernetes_io_master=\"true\"})/100"
      }
     ]
    },
    {
     "title": "Infra Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Used Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_infra=\"true\"}[1m]))"
      }
     ]
    },
    {
     "title": "Millicore Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_spec_cpu_quota{node_role_kubernetes_io_infra=\"true\"})/100"
      }
     ]
    },
    {
     "title": "App Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"}) "
      }
     ]
    },
    {
     "title": "Used Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node_role_kubernetes_io_compute=\"true\"}[1m]))"
      }
     ]
    },
    {
     "title": "Millicore Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 64 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_spec_cpu_quota{node_role_kubernetes_io_compute=\"true\"})/100"
      }
     ]
    },
    {
     "title": "CPU Millicore Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 67 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota)/100) / (sum (machine_cpu_cores)*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Millicore Limit Allocation for Masters",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 67 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota{node_role_kubernetes_io_master=\"true\"})/100) / (sum (machine_cpu_cores)*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Millicore Limit Allocation for Infra",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 67 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota{node_role_kubernetes_io_infra=\"true\"})/100) / (sum (machine_cpu_cores)*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Millicore Limit Allocation for App",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 67 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_cpu_quota{node_role_kubernetes_io_compute=\"true\"})/100) / (sum (machine_cpu_cores)*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Request Allocation",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 70 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"})*1000)) / (sum (machine_cpu_cores)*1000)  * 100 "
      }
     ]
    },
    {
     "title": "CPU Request Allocation per Project",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 70 },
     "yaxes": [
      { "format": "none", "label": "millicores" }
     ],
     "targets": [
      {
       "expr": "sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"})*1000) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100"
      }
     ]
    },
    {
     "title": "Master Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_master=\"true\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\"})* 100"
      }
     ]
    },
    {
     "title": "Infra Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 71 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_infra=\"true\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\"})* 100"
      }
     ]
    },
    {
     "title": "App Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 71 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_compute=\"true\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 76 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      { "expr": "sum (machine_memory_bytes)" }
     ]
    },
    {
     "title": "Total Mem Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 76 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
      }
     ]
    },
    {
     "title": "Total Mem Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 76 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_spec_memory_limit_bytes{pod_name!=\"\"})"
      }
     ]
    },
    {
     "title": "Master Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 76 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Master Mem Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 76 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_master=\"true\"})"
      }
     ]
    },
    {
     "title": "Master Mem Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 76 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_master=\"true\",pod_name!=\"\"})"
      }
     ]
    },
    {
     "title": "Infra Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 76 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Infra Mem Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 76 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_infra=\"true\"})"
      }
     ]
    },
    {
     "title": "Infra Mem Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 76 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_infra=\"true\",pod_name!=\"\"})"
      }
     ]
    },
    {
     "title": "App Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 76 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "App Mem Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 76 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "App Memory Limits",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 76 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_compute=\"true\",pod_name!=\"\"})"
      }
     ]
    },
    {
     "title": "Total Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 79 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_memory_limit_bytes{pod_name!=\"\"})) / (sum (machine_memory_bytes))  * 100 "
      }
     ]
    },
    {
     "title": "Master Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 79 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_master=\"true\"})) / (sum (machine_memory_bytes))  * 100 "
      }
     ]
    },
    {
     "title": "Infra Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 79 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_infra=\"true\"})) / (sum (machine_memory_bytes))  * 100 "
      }
     ]
    },
    {
     "title": "App Memory Limit Allocation",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 79 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_memory_limit_bytes{node_role_kubernetes_io_compute=\"true\"})) / (sum (machine_memory_bytes))  * 100 "
      }
     ]
    },
    {
     "title": "Memory Request Allocation",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 81 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum (container_spec_memory_limit_bytes{pod_name!=\"\"})) / (sum (machine_memory_bytes))  * 100 "
      }
     ]
    },
    {
     "title": "Memory Request Allocation per Project",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 81 },
     "yaxes": [
      { "format": "bytes", "label": "memory" }
     ],
     "targets": [
      {
       "expr": "sum ((kube_pod_container_resource_requests_memory_bytes)) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods per Node",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum (kube_pod_info) by (node)", "legendFormat": "{{ node }}" }
     ]
    }
   ]
  },
  {
   "title": "Openshift / Kubernetes Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Information",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 83 },
     "targets": [
      { "expr": "kube_node_info" }
     ]
    }
   ]
  }
 ]
}