---
- name: restart iptables
  service: name=iptables state=restarted

- name: restart master api
  systemd: name=origin-master-api state=restarted
  when:
    - openshift_release is version('3.10', '<')
  notify: verify API server

- name: restart master controllers
  systemd: name=origin-master-controllers state=restarted
  when:
    - openshift_release is version('3.10', '<')

- name: restart master
  command: /usr/local/bin/master-restart "{{ item }}"
  with_items:
  - api
  - controllers
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0
  notify: verify API server
  when:
    - openshift_release is version('3.10', '>=')

- name: verify API server
  command: >
    curl --silent --tlsv1.2 --insecure
    https://localhost:8443/healthz/ready
  args:
    warn: no
  register: api_available_output
  until: api_available_output.stdout == 'ok'
  retries: 120
  delay: 1
  changed_when: false
