- name: Restore InfluxDB from backups
  hosts: masters
  run_once: true
  gather_facts: yes
  vars:
  - restore_job_number: "{{ ansible_date_time.epoch }}"
  tasks:
  - name: upsert restore job
    include: tasks/upsert_k8s_object.yml
    vars:
      namespace: monitoring-infra
      template_base_name: restore_influxdb.yml.j2
      name: restore_influxdb

  - name: wait for the restore to finish
    shell: >
      oc get jobs/restore-influxdb-{{ restore_job_number }}
      -o template
      --template="{{ '{{' }}.status.succeeded{{ '}}' }}"
      -n monitoring-infra
    register: result
    until: ("1" in result.stdout)
    retries: 50
    delay: 10
    changed_when: false

  - name: restore access to prometheus db for the prom_reader user
    uri:
      url: http://influxdb.monitoring-infra.svc.cluster.local:8086/query
      method: POST
      body: "q=GRANT READ ON \"prometheus\" TO \"prom_reader\""
      user: "admin"
      password: "{{ monitoring_access_token }}"
      status_code:
      - 200
