- set_fact: vg_name=vg_{{ volume_spec.name }}

- set_fact: pv_path={{ volume_spec.pv_path }}

- name: Scan for {{ vg_name }} volume group
  command: vgdisplay {{ vg_name }}
  register: test_vg
  ignore_errors: yes
  failed_when: false
  changed_when: false
  
# Make sure we don't configure disks in Rahti compute, if we have customer vols attached
# Rahti compute uses the iSCSI disk driver insead of virtio, so disks are /dev/sd* not /dev/vd*
# All other systems use /dev/vd* 

- name: Check if production compute nodes have customer vols attached
  assert: 
    that: 
      - ansible_device_links["ids"]["sdc"] is undefined
  when: test_vg.rc==5

# in case the volumes were there, activate them in case they are reused from a previous incarnation
# TODO: replace with lvol based activation available in ansible 2.2
- name: activate lvs
  command: vgchange -ay {{ vg_name }}
  changed_when: false
  when: test_vg.rc!=5

# Ansible's vg module creates a pv if neccessary
- name: Create volume group {{ vg_name }} on {{ pv_path }}
  lvg: vg={{ vg_name }} pvs={{ pv_path }}
  when: test_vg.rc==5
