- name: Enable Openshift mutating admission webhook API
  yedit:
    src: "{{ openshift_master_config_file }}"
    key: admissionConfig.pluginConfig.MutatingAdmissionWebhook
    value: |
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
  notify:
    - restart master
    - restart master api
