---
- name: ensure that the webconsole-config configMap is patched
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: webconsole-config
        namespace: "{{ webconsole_namespace }}"
      data:
        webconsole-config.yaml: |
          apiVersion: webconsole.config.openshift.io/v1
          kind: WebConsoleConfiguration
          clusterInfo:
            consolePublicURL: https://{{ openshift_public_hostname }}:8443/console/
            loggingPublicURL: ''
            logoutPublicURL: ''
            masterPublicURL: https://{{ openshift_public_hostname }}:8443
            metricsPublicURL: https://hawkular-metrics.{{ openshift_app_domain|default(openshift_public_hostname) }}/hawkular/metrics
            adminConsolePublicURL: https://console.{{ openshift_app_domain|default(openshift_public_hostname) }}/
          extensions:
            scriptURLs: []
            stylesheetURLs:
              - {{ webconsole_logo_extension_url }}
            properties: {}
          features:
            inactivityTimeoutMinutes: 0
            clusterResourceOverridesEnabled: false
          servingInfo:
            bindAddress: 0.0.0.0:8443
            bindNetwork: tcp4
            certFile: /var/serving-cert/tls.crt
            clientCA: ''
            keyFile: /var/serving-cert/tls.key
            maxRequestsInFlight: 0
            namedCertificates:
            requestTimeoutSeconds: 0
  register: webconsole_config

- name: scale down the webconsole pods to 0
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: webconsole
        namespace: openshift-web-console
      spec:
        replicas: 0
  when: webconsole_config.changed

- name: scale up the webconsole pods back to 1
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: webconsole
        namespace: "{{ webconsole_namespace }}"
      spec:
        replicas: 1
  when: webconsole_config.changed
