apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: Minio
message: |-
  Minio has been scheduled for creation in your project, and should be soon available at: https://${CLUSTER_NAME}.${DOMAINSUFFIX}

metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
    description: This template deploys an S3 compatible private Object Storage based on Minio.


      The backend storage can be either a new or an existing persistent volume claim (PVC).


      In case you want to use existing PVC for Minio Storage, please update PVC name with the PVC you want to use.
      In this case, Rahti will issue an error that no new PVC is created but proceeds with creating the rest of the
      application nevertheless.

    tags: S3, Object Store
    openshift.io/display-name: Minio Object Store
    iconClass: fa fa-archive
    openshift.io/provider-display-name: CSC-IT Center for Science Ltd.
    openshift.io/documentation-url: https://github.com/CSCfi/Minio-OpenShift/blob/master/README.md
    openshift.io/support-url: https://www.csc.fi/contact-info
  name: minio

objects:
# Minio part
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ${CLUSTER_NAME}
      spec:
        initContainers:
        - image: alpine
          command: ["/bin/sh","-c","if [ ! -f /data/files/.minio.sys/config/config.json ]; then mkdir -p /data/files/.minio.sys/config/; cp /mnt/default-config-json/config.json /data/files/.minio.sys/config/config.json; fi" ]
          name: config-init
          volumeMounts:
          - mountPath: /data/files                                                                                                                                                      
            name: minio-vol  
          - mountPath: /mnt/default-config-json/
            name: default-config-json
        containers:
        - image: minio/minio:RELEASE.2022-10-24T18-35-07Z
          name: ${CLUSTER_NAME}
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
              scheme: HTTP
          livelinessProbe:
            httpGet:
              path: /health/live
              port: 9000
              scheme: HTTP
          volumeMounts:
          - mountPath: /data/files
            name: minio-vol
          command:
          - minio
          - server
          - /data/files
          - --console-address
          - :9001
          env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: ${CLUSTER_NAME}-secret
                key: accessKey
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${CLUSTER_NAME}-secret
                key: secretKey
        volumes:
        - name: minio-vol
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - configMap:
            defaultMode: 420
            name: default-config-json
          name: default-config-json
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-secret
    labels:
      app: ${CLUSTER_NAME}
  type: Opaque                     # Unstructured secret
  stringData:
    accessKey: ${ROOT_USER}
    secretKey: ${ROOT_PASSWORD}

- apiVersion: v1
  data:
    config.json: '{"api":{"_":[{"key":"requests_max","value":"0"},{"key":"requests_deadline","value":"10s"},{"key":"cluster_deadline","value":"10s"},{"key":"cors_allow_origin","value":"*"},{"key":"remote_transport_deadline","value":"2h"},{"key":"list_quorum","value":"strict"},{"key":"replication_workers","value":"250"},{"key":"replication_failed_workers","value":"8"},{"key":"transition_workers","value":"100"},{"key":"stale_uploads_cleanup_interval","value":"6h"},{"key":"stale_uploads_expiry","value":"24h"},{"key":"delete_cleanup_interval","value":"5m"}]},"audit_kafka":{"_":[{"key":"enable","value":"off"},{"key":"topic","value":""},{"key":"brokers","value":""},{"key":"sasl_username","value":""},{"key":"sasl_password","value":""},{"key":"sasl_mechanism","value":"plain"},{"key":"client_tls_cert","value":""},{"key":"client_tls_key","value":""},{"key":"tls_client_auth","value":"0"},{"key":"sasl","value":"off"},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"version","value":""}]},"audit_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""}]},"cache":{"_":[{"key":"drives","value":""},{"key":"exclude","value":""},{"key":"expiry","value":"90"},{"key":"quota","value":"80"},{"key":"after","value":"0"},{"key":"watermark_low","value":"70"},{"key":"watermark_high","value":"80"},{"key":"range","value":"on"},{"key":"commit","value":"writethrough"}]},"compression":{"_":[{"key":"enable","value":"off"},{"key":"allow_encryption","value":"off"},{"key":"extensions","value":".txt,.log,.csv,.json,.tar,.xml,.bin"},{"key":"mime_types","value":"text/*,application/json,application/xml,binary/octet-stream"}]},"credentials":{"_":[{"key":"access_key","value":"minioadmin"},{"key":"secret_key","value":"minioadmin"}]},"etcd":{"_":[{"key":"endpoints","value":""},{"key":"path_prefix","value":""},{"key":"coredns_path","value":"/skydns"},{"key":"client_cert","value":""},{"key":"client_cert_key","value":""}]},"heal":{"_":[{"key":"bitrotscan","value":"off"},{"key":"max_sleep","value":"1s"},{"key":"max_io","value":"100"}]},"identity_ldap":{"_":[{"key":"server_addr","value":""},{"key":"user_dn_search_base_dn","value":""},{"key":"user_dn_search_filter","value":""},{"key":"group_search_filter","value":""},{"key":"group_search_base_dn","value":""},{"key":"tls_skip_verify","value":"off"},{"key":"server_insecure","value":"off"},{"key":"server_starttls","value":"off"},{"key":"lookup_bind_dn","value":""},{"key":"lookup_bind_password","value":""}]},"identity_openid":{"_":[{"key":"config_url","value":""},{"key":"client_id","value":""},{"key":"client_secret","value":""},{"key":"claim_name","value":"policy"},{"key":"claim_userinfo","value":""},{"key":"claim_prefix","value":""},{"key":"redirect_uri","value":""},{"key":"scopes","value":""},{"key":"jwks_url","value":""}]},"identity_tls":{"_":[{"key":"skip_verify","value":"off"}]},"logger_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""}]},"notify_amqp":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"exchange","value":""},{"key":"exchange_type","value":""},{"key":"routing_key","value":""},{"key":"mandatory","value":"off"},{"key":"durable","value":"off"},{"key":"no_wait","value":"off"},{"key":"internal","value":"off"},{"key":"auto_deleted","value":"off"},{"key":"delivery_mode","value":"0"},{"key":"publisher_confirms","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""}]},"notify_elasticsearch":{"_":[{"key":"enable","value":"off"},{"key":"url","value":""},{"key":"format","value":"namespace"},{"key":"index","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"username","value":""},{"key":"password","value":""}]},"notify_kafka":{"_":[{"key":"enable","value":"off"},{"key":"topic","value":""},{"key":"brokers","value":""},{"key":"sasl_username","value":""},{"key":"sasl_password","value":""},{"key":"sasl_mechanism","value":"plain"},{"key":"client_tls_cert","value":""},{"key":"client_tls_key","value":""},{"key":"tls_client_auth","value":"0"},{"key":"sasl","value":"off"},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""},{"key":"version","value":""}]},"notify_mqtt":{"_":[{"key":"enable","value":"off"},{"key":"broker","value":""},{"key":"topic","value":""},{"key":"password","value":""},{"key":"username","value":""},{"key":"qos","value":"0"},{"key":"keep_alive_interval","value":"0s"},{"key":"reconnect_interval","value":"0s"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_mysql":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"dsn_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"max_open_connections","value":"2"}]},"notify_nats":{"_":[{"key":"enable","value":"off"},{"key":"address","value":""},{"key":"subject","value":""},{"key":"username","value":""},{"key":"password","value":""},{"key":"token","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"cert_authority","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""},{"key":"ping_interval","value":"0"},{"key":"streaming","value":"off"},{"key":"streaming_async","value":"off"},{"key":"streaming_max_pub_acks_in_flight","value":"0"},{"key":"streaming_cluster_id","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_nsq":{"_":[{"key":"enable","value":"off"},{"key":"nsqd_address","value":""},{"key":"topic","value":""},{"key":"tls","value":"off"},{"key":"tls_skip_verify","value":"off"},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_postgres":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"connection_string","value":""},{"key":"table","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"},{"key":"max_open_connections","value":"2"}]},"notify_redis":{"_":[{"key":"enable","value":"off"},{"key":"format","value":"namespace"},{"key":"address","value":""},{"key":"key","value":""},{"key":"password","value":""},{"key":"queue_dir","value":""},{"key":"queue_limit","value":"0"}]},"notify_webhook":{"_":[{"key":"enable","value":"off"},{"key":"endpoint","value":""},{"key":"auth_token","value":""},{"key":"queue_limit","value":"0"},{"key":"queue_dir","value":""},{"key":"client_cert","value":""},{"key":"client_key","value":""}]},"policy_opa":{"_":[{"key":"url","value":""},{"key":"auth_token","value":""}]},"region":{"_":[{"key":"name","value":""}]},"scanner":{"_":[{"key":"delay","value":"10"},{"key":"max_wait","value":"15s"},{"key":"cycle","value":"1m"}]},"storage_class":{"_":null},"subnet":{"_":[{"key":"license","value":""}]}}'
  kind: ConfigMap
  metadata:
    name: default-config-json

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: 9001-console
      port: 9001
      protocol: TCP
    selector:
      app: ${CLUSTER_NAME}

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}
    annotations:
      haproxy.router.openshift.io/ip_whitelist: ${WHITELIST}
  spec:
    host: ${CLUSTER_NAME}.${DOMAINSUFFIX}
    port:
      targetPort: 9000
    to:
      kind: Service
      name: ${CLUSTER_NAME}
      weight: 100
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}-console
    annotations:
      haproxy.router.openshift.io/ip_whitelist: ${WHITELIST}
  spec:
    host: ${CLUSTER_NAME}-console.${DOMAINSUFFIX}
    port:
      targetPort: 9001
    to:
      kind: Service
      name: ${CLUSTER_NAME}
      weight: 100
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect


- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: ${PVCNAME}
    labels:
      app: ${CLUSTER_NAME}
  spec:
    storageClassName: glusterfs-storage
    accessModes:
      - "ReadWriteMany"
    resources:
      requests:
        storage: ${STORAGE_SIZE}

parameters:
  - name: ROOT_USER
    required: true
    description: Root user, its length should be between minimum 3 characters.
    displayName: Root user
    from: '[a-zA-Z0-9]{32}'
    generate: expression

  - name: ROOT_PASSWORD
    description: Root password, its length should be between 8 & 40 characters.
    displayName: Root password
    required: true
    from: '[a-zA-Z0-9]{32}'
    generate: expression

  - name: CLUSTER_NAME
    description: "Name of the minio cluster instance. Must be DNS label compatible: alphanumeric, `-` and `.` characters are only allowed. The application can be reached at CLUSTER_NAME.DOMAINSUFFIX."
    displayName: Cluster name
    required: true

  - name: DOMAINSUFFIX
    required: true
    description: Hostname suffix of the application.
    displayname: Hostname suffix of the application.
    value: rahtiapp.fi

  - name: PVCNAME
    required: true
    description: PVC name to mount for minio buckets
    displayName: PVC Volume name
    value: minio-default-volume

  - name: STORAGE_SIZE
    required: true
    description: Object storage backend volume size
    displayname: Storage size
    value: 1Gi

  - name: WHITELIST
    required: false
    description: IP whitelist for the application. Must not contain errors, otherwise Rahti will allow all traffic.
    displayname: Route whitelist
    value: 0.0.0.0/0
