---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Rocket.Chat
  name: rocket.chat
spec:
  tags:
    - name: "0.58.2"
      annotations:
        description: >
          Provides Rocket.Chat 0.58.2 from the official Docker image.
        openshift.io/display-name: Rocket.Chat 0.58.2
        tags: rocket.chat
        version: "0.58.2"
      from:
        kind: DockerImage
        name: rocketchat/rocket.chat:0.58.2
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: latest
      annotations:
        description: >
          Provides the latest Rocket.Chat available in this OpenShift installation.
        openshift.io/display-name: Rocket.Chat (latest)
        tags: rocket.chat
      from:
        kind: ImageStreamTag
        name: "0.58.2"
      importPolicy: {}
      referencePolicy:
        type: Source
