- name: disable auto-updates on Pouta (these can cause container restarts)
  file:
    name: /etc/cron.daily/automatic_updates
    state: absent

- name: upload custom docker storage configuration for docker-storage-setup
  template:
    src: etc/sysconfig/docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    backup: True

- name: create /etc/docker directory if it does not exist
  file:
    path: /etc/docker
    state: directory

- name: limit the size of docker logs to {{ docker_logs_size_limit }}
  template:
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: True

- name: install Red Hat certificate bundle
  yum:
    name: "python-rhsm-certificates"
    state: present

- name: fallback for missing certificate bundle file on early CentOS 7.5
  copy:
    dest: /etc/rhsm/ca/redhat-uep.pem
    src: files/etc/rhsm/ca/redhat-uep.pem
    mode: 0644
    owner: root

- name: set {{ docker_package_name }} state to {{ docker_package_state }}
  yum:
    name: "{{ docker_package_name }}"
    state: "{{ docker_package_state }}"
  when:
    - docker_package_state != 'noop'

- name: start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  when:
    - docker_package_state in ['present', 'latest', 'installed']
