- name: disable auto-updates on Pouta
  file:
    name: /etc/cron.daily/automatic_updates
    state: absent

- name: templatize base repo config file
  template:
    src: base.repo.j2
    dest: /etc/yum.repos.d/CentOS-Base.repo
  register: templatize_base_repo_config_file

- name: optionally lock operating system minor version in repo config
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "http://vault.centos.org/centos/{{ os_version | default(ansible_distribution_version) }}/{{ item.subpath }}/$basearch/"
    description: "CentOS-{{ os_version | default(ansible_distribution_version) }} - {{ item.name }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: yes
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
  with_items:
    - name: 'base'
      subpath: 'os'
      enabled: "{{ (lock_os_minor_version|default(false)|bool) | ternary('1', '0') }}"
    - name: 'updates'
      subpath: 'updates'
      enabled: "{{ (lock_os_minor_version|default(false)|bool) | ternary('1', '0') }}"
    - name: 'extras'
      subpath: 'extras'
      enabled: "{{ (lock_os_minor_version|default(false)|bool) | ternary('1', '0') }}"
    - name: 'centosplus'
      subpath: 'centosplus'
      enabled: no
  register: create_locked_yum_repo_configs

- name: yum clean metadata
  command: yum clean metadata
  args:
    warn: no
  when: templatize_base_repo_config_file.changed or create_locked_yum_repo_configs.changed

- name: install basic tools
  yum: pkg={{item}} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - git
    - xauth
    - screen
    - nano
    - vim
    - bind-utils
    - nmap-ncat
    - lvm2
    - chrony
    - bzip2
    - iptables
    - iptables-services
    - NetworkManager
    - jq
    - sysstat
    - logrotate
    - python-pip

- name: install virtualenv for Python
  pip: name=virtualenv state=present

- name: disable kdump
  service:
    name: kdump
    state: stopped
    enabled: no
  register: kdump_status

- name: reset failed units in systemd if needed
  command: systemctl reset-failed
  when: kdump_status.changed

- name: stop cloud-init managing /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/10_etc_hosts.cfg
    state: present
    regexp: '^manage_etc_hosts'
    line: 'manage_etc_hosts: False'
    create: yes

- name: fix /etc/hosts after cloud-init
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: "^127.0.0.1(.*){{ inventory_hostname }}(.*)"

- name: remove ntp.org pool hosts from config
  lineinfile:
    dest: /etc/chrony.conf
    state: absent
    regexp: '^server .*ntp.org iburst'
  when: custom_ntp_servers is defined
  notify: restart chronyd

- name: add custom servers to NTP config
  lineinfile:
    dest: /etc/chrony.conf
    state: present
    line: 'server {{ item }} iburst'
  with_items: '{{ custom_ntp_servers|default([]) }}'
  when: custom_ntp_servers is defined
  notify: restart chronyd

- name: start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - NetworkManager
    - chronyd

- include: rng.yml
