---
heat_template_version: newton

description: >
  A volume that is attached to a specific instance. For use with ResourceGroups.

parameters:
  instance_id:
    type: string
  volume_name:
    type: string
  volume_size:
    type: string

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: volume_name }
      size: { get_param: volume_size }

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_param: instance_id }
      volume_id: { get_resource: volume }
