- name: add OPENSHIFT-FIREWALL-ALLOW chain so that we can refer to it
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '^:OUTPUT ACCEPT'
    line: ':OPENSHIFT-FIREWALL-ALLOW - [0:0]'
  when: "'masters' not in group_names"
  notify: restart iptables

- name: block access from SDN to internal network (INPUT)
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT'
  # here we insert our own blocking rule and the rules that would be inserted by OpenShift as well to prevent
  # OpenShift overriding our rule. see https://trello.com/c/vwOxBiXn/253-iptables-make-it-possible-to-specify-the-chain-in-which-to-insert-the-accept-vxlan-rule-operations
    block: |
      -A INPUT -s 10.128.0.0/14 -d 192.168.0.0/16 -p udp -m udp --dport 53 -j ACCEPT
      -A INPUT -s 10.128.0.0/14 -d 192.168.0.0/16 -p tcp -m tcp --dport 53 -j ACCEPT
      -A INPUT -d 192.168.0.0/16 -i tun0 -j REJECT --reject-with icmp-port-unreachable
      -A INPUT -m comment --comment "firewall overrides" -j OPENSHIFT-FIREWALL-ALLOW
      -A INPUT -s 192.168.0.0/16 -j ACCEPT
    marker: '-A INPUT -m comment --comment "{mark} ANSIBLE MANAGED BLOCK INPUT"'
  when: "'masters' not in group_names"
  notify: restart iptables

- name: add OPENSHIFT-ADMIN-OUTPUT-RULES chain
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '^:OUTPUT ACCEPT'
    line: ':OPENSHIFT-ADMIN-OUTPUT-RULES - [0:0]'
  when: "'masters' not in group_names"
  notify: restart iptables

- name: block access from SDN to internal network (OPENSHIFT-ADMIN-OUTPUT-RULES)
  blockinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '^-A FORWARD -j REJECT'
    block: |
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -s 10.128.0.0/14 -d 192.168.0.0/16 -p udp -m udp --dport 53 -j ACCEPT
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -s 10.128.0.0/14 -d 192.168.0.0/16 -p tcp -m tcp --dport 53 -j ACCEPT
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -s 10.128.0.0/14 -d 192.168.0.0/16 -p tcp -m tcp --dport 8443 -j ACCEPT
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -s 10.128.0.0/14 -d 192.168.0.0/16 -j REJECT --reject-with icmp-port-unreachable
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -s 10.128.0.0/14 -j ACCEPT
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -d 10.128.0.0/14 -j ACCEPT
      -A OPENSHIFT-ADMIN-OUTPUT-RULES -j RETURN
    marker: '-A OPENSHIFT-ADMIN-OUTPUT-RULES -m comment --comment "{mark} ANSIBLE MANAGED BLOCK OPENSHIFT-ADMIN-OUTPUT-RULES"'
  when: "'masters' not in group_names"
  notify: restart iptables

- name: add a cron entry for restarting rsyslog
  cron:
    name: "Restart rsyslog"
    hour: "04"
    minute: "{{ 59|random(seed=ansible_host) }}"
    cron_file: poc_restart_rsyslog
    user: root
    job: "systemctl restart rsyslog"
