apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request-default
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}
  userNames: null
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}

# custom additions start here

# Quota
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources
  spec:
    hard:
      pods: "{{ default_project_pod_num_quota | default('20') }}"
    scopes:
    - NotTerminating

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: storage-resources
  spec:
    hard:
      requests.storage: "{{ storage_default_quota|default('50Gi') }}"

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: openshift-object-counts
  spec:
    hard:
      openshift.io/imagestreams: "{{ default_project_images_number_max_limit | default('10') }}"

# Limit range
- apiVersion: "v1"
  kind: "LimitRange"
  metadata:
    name: "core-resource-limits"
  spec:
    limits:
      - type: "Pod"
        max:
          cpu: "{{ default_project_pod_cpu_max_limit | default('2') }}"
          memory: "{{ default_project_pod_mem_max_limit | default('8Gi') }}"
        min:
          cpu: "{{ default_project_pod_cpu_min_limit | default('50m') }}"
          memory: "{{ default_project_pod_mem_min_limit | default('6Mi') }}"
      - type: "Container"
        max:
          cpu: "{{ default_project_container_cpu_max_limit | default('2') }}"
          memory: "{{ default_project_container_mem_max_limit | default('8Gi') }}"
        min:
          cpu: "{{ default_project_container_cpu_min_limit | default('50m') }}"
          memory: "{{ default_project_container_mem_min_limit | default('4Mi') }}"
        defaultRequest:
          cpu: "{{ default_project_default_container_cpu_request | default('50m') }}"
          memory: "{{ default_project_default_container_mem_request | default('200Mi') }}"
      - type: "openshift.io/Image"
        max:
          storage: "{{ default_project_image_size_max_limit | default('5Gi') }}"

# custom additions end here

parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
