- name: create inventory.yaml configuration file
  template:
    src: inventory.yaml.j2
    dest: "{{ openshift_installer_dir }}/inventory.yaml"

- name: create installer manifests
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: ./openshift-install create manifests

- name: remove Machines and MachineSets
  file:
    path: "{{ openshift_installer_dir }}/openshift/99_openshift-cluster-api_*-machines-*.yaml"
    state: absent

- name: copy make-unschedulable.py to installer folder
  copy:
    src: make-unschedulable.py
    dest: "{{ openshift_installer_dir }}/make-unschedulable.py"

- name: run make-unschedulable.py
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: python make-unschedulable.py

- name: create ignition configs
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: ./openshift-install create ignition-configs

- name: get infra ID
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: jq -r .infraID metadata.json
  register: infra_id

- name: debug infra id
  debug:
    var: infra_id

- name: copy edit-bootstrap-ignition.py to installer folder
  copy:
    src: edit-bootstrap-ignition.py
    dest: "{{ openshift_installer_dir }}/edit-bootstrap-ignition.py"

- name: run edit-bootstrap-ignition.py
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: python edit-bootstrap-ignition.py
  environment:
    INFRA_ID: "{{ infra_id.stdout }}"

# TODO: upload bootstrap ignition files to swift bucket

- name: copy edit-master-ignition.sh to installer folder
  copy:
    src: edit-master-ignition.sh
    dest: "{{ openshift_installer_dir }}/edit-master-ignition.sh"

# NOTE: This script is hard-coded to expect 3 master nodes
- name: run edit-master-ignition.sh
  command:
    chdir: "{{ openshift_installer_dir }}"
    cmd: sh edit-master-ignition.sh
  environment:
    INFRA_ID: "{{ infra_id.stdout }}"

# TODO: figure out where to store bootstrap ignition file
- name: create bootstrap-ignition.json configuration file
  template:
    src: bootstrap-ignition.json.j2
    dest: "{{ openshift_installer_dir }}/{{ infra_id.stdout }}-bootstrap-ignition.json"
