---
- name: Setup OAuth authentication providers
  yedit:
    src: "{{ openshift_master_config_file }}"
    key: oauthConfig.identityProviders
    value: |
      - name: Local account
        login: true
        mappingMethod: add
        challenge: true
        provider:
          apiVersion: v1
          file: /etc/origin/master/htpasswd
          kind: HTPasswdPasswordIdentityProvider
      {% if deploy_github_auth | d() | bool == true -%}
      - name: GitHub
        challenge: false
        login: true
        mappingMethod: add
        provider:
          apiVersion: v1
          kind: GitHubIdentityProvider
          clientID: "{{ github_oauth_client_id }}"
          clientSecret: "{{ github_oauth_client_secret }}"
          organizations:
      {% for org in github_allowed_auth_orgs %}
            - {{ org }}
      {% endfor %}
      {%- endif %}
      {% if deploy_gitlab_auth | d() | bool == true -%}
      - name: "{{ gitlab_oauth_provider_name }}"
        challenge: true
        login: true
        mappingMethod: add
        provider:
          apiVersion: v1
          kind: GitLabIdentityProvider
          url: "{{ gitlab_url }}"
          clientID: "{{ gitlab_oauth_client_id }}"
          clientSecret: "{{ gitlab_oauth_client_secret }}"
      {%- endif %}
  notify:
    - restart master
    - restart master api
