---
- name: Setup OAuth authentication providers
  yedit:
    src: "{{ openshift_master_config_file }}"
    key: oauthConfig.identityProviders
    value: |
      - name: Local account
        login: true
        mappingMethod: "{{ local_auth_mapping_method }}"
        challenge: true
        provider:
          apiVersion: v1
          file: /etc/origin/master/htpasswd
          kind: HTPasswdPasswordIdentityProvider
      {% if deploy_github_auth | d() | bool == true -%}
      - name: GitHub
        challenge: false
        login: true
        mappingMethod: "{{ github_auth_mapping_method }}"
        provider:
          apiVersion: v1
          kind: GitHubIdentityProvider
          clientID: "{{ github_oauth_client_id }}"
          clientSecret: "{{ github_oauth_client_secret }}"
          organizations:
      {% for org in github_allowed_auth_orgs %}
            - {{ org }}
      {% endfor %}
      {% endif %}
      {% if deploy_gitlab_auth | d() | bool == true -%}
      - name: "{{ gitlab_oauth_provider_name }}"
        challenge: true
        login: true
        mappingMethod: "{{ gitlab_auth_mapping_method }}"
        provider:
          apiVersion: v1
          kind: GitLabIdentityProvider
          url: "{{ gitlab_url }}"
          clientID: "{{ gitlab_oauth_client_id }}"
          clientSecret: "{{ gitlab_oauth_client_secret }}"
      {% endif %}
      {% if deploy_ldap_auth | d() | bool == true -%}
      - name: "{{ ldap_auth_provider_name }}"
        challenge: true
        login: true
        mappingMethod: "{{ ldap_auth_mapping_method }}"
        provider:
          apiVersion: v1
          kind: LDAPPasswordIdentityProvider
          attributes:
      {% for key in ldap_attribute_map %}
            {{ key }}:
      {% for value in ldap_attribute_map[key] %}
              - {{ value }}
      {% endfor %}
      {% endfor %}
          insecure: false
      {% if ldap_bind_account_dn is defined %}
          bindDN: "{{ ldap_bind_account_dn }}"
      {% endif %}
      {% if ldap_bind_account_password is defined %}
          bindPassword: "{{ ldap_bind_account_password }}"
      {% endif %}
          url: "{{ ldap_user_query }}"
      {% endif %}
      {% if deploy_openid_connect_auth | d() | bool == true -%}
      - name: "{{ openid_connect_provider_name }}"
        challenge: true
        login: true
        mappingMethod: "{{ openid_connect_mapping_method }}"
        provider:
          apiVersion: v1
          kind: OpenIDIdentityProvider
          clientID: "{{ openid_connect_client_id }}"
          clientSecret: "{{ openid_connect_client_secret }}"
          claims:
            id:
            - sub
            preferredUsername:
            - preferred_username
            name:
            - name
            email:
            - email
          urls:
            authorize: "{{ openid_connect_authorize_url }}"
            token: "{{ openid_connect_token_url }}"
      {% endif %}
  notify:
    - restart master
    - restart master api

- name: populate/update htaccess file
  copy:
    dest: /etc/origin/master/htpasswd
    mode: 0600
    owner: root
    group: root
    content: |
      {% for user, pass in local_auth_mapping_htaccess_entries.iteritems() %}
      {{   user ~ ':' ~ pass }}
      {% endfor %}
