- name: add the glusterfs41 repo
  yum:
    pkg: centos-release-gluster41
    state: present

- name: install glusterfs
  yum:
    pkg: glusterfs-server
    state: present

- name: start and enable glusterd on boot
  systemd:
    name: glusterd
    state: started
    enabled: yes

- name: allow connections to glusterd in the cluster
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '^-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT'
    line: '-A INPUT -s 192.168.0.0/16 -d 192.168.0.0/16 -p tcp -m tcp --dport 24007 -j ACCEPT'
  register: iptables_config
  when:
    - not poc_installed|default(False) or poc_allow_iptables_update|default(false)

- name: restart iptables
  service: name=iptables state=restarted
  when: iptables_config.changed|default(false)

- name: probe glusterfs nodes
  run_once: true
  shell: "gluster peer probe {{ item }}"
  with_items: "{{ groups['glusterfs'] }}"
