- name: add the glusterfs9 repo
  retries: 3
  delay: 20
  register: yumresult
  until: yumresult.failed is false
  yum:
    pkg: centos-release-gluster9
    state: present
  when: "not poc_installed|default(False)"

- name: install glusterfs
  retries: 3
  delay: 20
  register: yumresult
  until: yumresult.failed is false
  yum:
    pkg: glusterfs-server
    state: present
  when: "not poc_installed|default(False)"

- name: start and enable glusterd on boot
  systemd:
    name: glusterd
    state: started
    enabled: yes
  when: "not poc_installed|default(False)"

- name: allow connections to glusterd in the cluster
  lineinfile:
    dest: /etc/sysconfig/iptables
    insertafter: '^-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT'
    line: '-A INPUT -s 192.168.0.0/16 -d 192.168.0.0/16 -p tcp -m tcp --dport 24007 -j ACCEPT'
  register: iptables_config
  when:
    - not poc_installed|default(False) or poc_allow_iptables_update|default(false)

- name: restart iptables
  service: name=iptables state=restarted
  when:
    - iptables_config.changed|default(false)
    - not poc_installed|default(False)

- name: list all the volume groupsvgs | grep "vg_" | awk '{ print $1 }'
  shell: vgs | grep "vg_" | awk '{ print $1 }'
  register: vg_list

- name: activate all the volume groups
  command: vgchange -ay {{ item }}
  with_items: "{{ vg_list.stdout_lines }}"

- name: mount all the bricks (External GlusterFS)
  command: "mount -a --fstab /etc/fstab"
  when: not poc_installed|default(False)

- name: probe glusterfs nodes
  run_once: true
  command: "gluster peer probe {{ item }}"
  with_items: "{{ groups['glusterfs'] }}"
