---
# Run projects lifecycle management script
# The {{ arguments }} variable is passed to the playbook using the ansible --extra-vars command line option
# Read more at docs/projects_lifecycle_management.md

- name: Create KubeConfig file
  hosts: masters
  gather_facts: false

  tasks:

    - name: Copy KubeConfig from master to deployment container
      ansible.builtin.fetch:
        src: ~/.kube/config
        dest: ~/.kube/config
        flat: yes
      run_once: true





