- name: Create poc service accounts
  hosts: masters
  run_once: true
  tasks:
  - name: create the service account
    include_role:
      name: openshift_service_accounts
    vars:
      name: "{{ item.name }}"
      namespace: "{{ item.namespace }}"
      roles: "{{ item.roles.split(',') }}"
    with_items: "{{ poc_service_accounts|default([]) }}"
