- name: Setup the egress IP ports
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - poc_facts
  tasks:
    - when: egress_ips is defined
      block:
      - name: source the floating IP IDs
        shell: "openstack floating ip show -f value -c id {{ item.floating_ip }}"
        register: floating_ip_ids
        with_items: "{{ egress_ips|default([]) }}"

      - name: append floating_ip_ids to the egress-ips array
        set_fact:
          heat_egress_ips: "{{ heat_egress_ips|default([]) + [item.0 | combine({'floating_ip_id': item.1.stdout})] }}"
        loop: "{{ egress_ips | zip(floating_ip_ids.results) | list }}"

      - name: create temp directory for templating
        command: mktemp -d
        register: mktemp
        changed_when: False

      - name: generate egress-ips Heat template definition
        copy:
          dest: "{{ mktemp.stdout }}/egress-ips.yml"
          content: "{{ lookup('template', 'files/heat/cluster-with-floating-ips/egress-ips.yml.j2') }}"

      - name: Build/update the egress IP Heat stack
        register: egress_ip_stack
        os_stack:
          name: "{{ cluster_name }}-egress-ips"
          state: present
          template: "{{ mktemp.stdout }}/egress-ips.yml"
          wait: yes
          parameters:
            network_id: "{{ cluster_name }}-network"

- name: Setup the namespaces with dedicated IPs
  hosts: masters
  run_once: true
  roles:
    - role: dedicated_namespace_ip
      vars:
        role_egress_ips: "{{ egress_ips|default([]) }}"
