---
- name: Deploy the monitoring stack
  hosts: masters
  strategy: linear # disable mitogen, would fail on python module import
  run_once: true
  roles:
    - role: poc_facts
    - role: cluster_monitoring
