# Additional configuration for masters.
# Currently configures:
#  - GitHub OAuth integration
#  - oc bash-completion
#  - Openshift admission webhooks API
#  - Restrict the number of namespaces per user
#  - Bash completion for oc
#  - Fixed certificate-authority-data for kubeconfig
---
- name: Additional master configuration
  hosts: masters
  serial: 1
  roles:
    - role: poc_facts

    - role: openshift_auth_providers
      when: configure_auth|default(true)|bool
      vars:
        local_auth_mapping_htaccess_entries: "{{ openshift_master_htpasswd_users }}"

    - role: openshift_admission_webhooks
      when: enable_openshift_admission_webhooks|default(false)|bool

    - role: openshift_limit_namespaces
      when: enable_openshift_limit_namespaces|default(true)|bool

    - role: openshift_login_page_logo
      when: login_page_logo_url is defined

    - role: openshift_ingress_ips
      when: ingress_ips_cidr is defined
  tasks:
    - name: generate bash completion with oc
      shell: oc completion bash > /etc/bash_completion.d/oc
      args:
        creates: /etc/bash_completion.d/oc

    - name: fix certificate-authority-data in kubeconfigs (needed to make k8s module work)
      kubeclient_ca:
        client_path: "{{ item }}"
        ca_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt"
      when: install_type == 'multimaster'
      with_items:
        - '/root/.kube/config'
        - '/home/cloud-user/.kube/config'
