# Additional configuration for masters.
# Currently configures:
#  - GitHub OAuth integration
#  - oc bash-completion
#  - Openshift admission webhooks API
#  - Restrict the number of namespaces per user
#  - Bash completion for oc
#  - Fixed certificate-authority-data for kubeconfig
---
- name: Additional master configuration
  hosts: masters
  serial: 1
  roles:
    - role: poc_facts

    - role: openshift_auth_providers
      when: configure_auth|default(true)|bool
      vars:
        local_auth_mapping_htaccess_entries: "{{ openshift_master_htpasswd_users }}"

    - role: openshift_admission_webhooks
      when: enable_openshift_admission_webhooks|default(false)|bool

    - role: openshift_limit_namespaces
      when: enable_openshift_limit_namespaces|default(true)|bool

    - role: openshift_login_page_logo
      when: login_page_logo_url is defined
  tasks:
    - name: generate bash completion with oc
      shell: oc completion bash > /etc/bash_completion.d/oc
      args:
        creates: /etc/bash_completion.d/oc

    - name: fix certificate-authority-data in kubeconfigs (needed to make k8s module work)
      kubeclient_ca:
        client_path: "{{ item }}"
        ca_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt"
      when: install_type == 'multimaster'
      with_items:
        - '/root/.kube/config'
        - '/home/cloud-user/.kube/config'

    # Update python setuptools for kubernetes module
    # https://github.com/kubernetes-client/python/issues/551
    - name: update setuptools
      pip:
        name: setuptools
        state: forcereinstall

    # k8s module requires specific version of kubernetes python module
    # Version 12 breaks default configuration handling
    # https://github.com/openshift/openshift-restclient-python/issues/389
    # This broke our site.yml and CI pipeline in November 2020
    - name: fix kubernetes python library version for k8s ansible module
      retries: 3
      delay: 20
      register: pipresult
      until: pipresult.failed is false
      pip:
        name:
          - kubernetes==10.1.0
          # include pyyaml and ipaddress to avoid uninstall failures
          - pyyaml
          - ipaddress
        state: present
