# Additional configuration for masters.
# Currently configures:
#  - GitHub OAuth integration
#  - oc bash-completion
#  - Openshift admission webhooks API
#  - Restrict the number of namespaces per user
---
- name: Additional master configuration
  hosts: masters
  serial: 1
  roles:
    - role: poc_facts

    - role: openshift_auth_providers
      when: configure_auth|default(true)|bool
      vars:
        local_auth_mapping_htaccess_entries: "{{ openshift_master_htpasswd_users }}"

    - role: openshift_admission_webhooks
      when: enable_openshift_admission_webhooks|default(false)|bool

    - role: openshift_limit_namespaces
      when: enable_openshift_limit_namespaces|default(true)|bool
  tasks:
    - name: generate bash completion with oc
      shell: oc completion bash > /etc/bash_completion.d/oc
      args:
        creates: /etc/bash_completion.d/oc
