---

- include: get_install_state.yml

- include: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/byo/config.yml"
  when:
    - groups['new_masters']|default([])|length == groups['masters']|default([])|length

- include: set_install_state.yml
