---

- import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/prerequisites.yml"

- import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/deploy_cluster.yml"
