- name: Additional master configuration
  include: extra_master_config.yml

- name: Additional OpenShift config via the API
  include: extra_oso_config.yml

- name: Additional Docker registry configuration
  include: registry_config.yml

- name: Setup default www app
  include: setup_default_www_app.yml

# There is a localhost -based play in deploy_monitoring, and it seems that even if the play
# includes environment_context for assigning variables for localhost, the tasks are culled early.
# That is why we need to get the installation flag from master[0]
- name: Deploy monitoring
  include: deploy_monitoring.yml
  when: hostvars[groups.masters[0]].deploy_monitoring|default(false)|bool

- name: Deploy app templates and related objects
  include: add_app_templates.yml
  when: add_app_templates|default(true)|bool

# Fix: make sure origin-master-controllers have up to date resolv.conf with local resolution
- name: Fix - restart master controllers
  include: fix_restart_master_controllers.yml
