- name: Additional master configuration
  import_playbook: extra_master_config.yml

- name: Set quota for emptyDir volumes
  import_playbook: set_compute_empydir_quota.yml
  when: poc_set_compute_empydir_quota|default(False)

- name: Additional OpenShift config via the API
  import_playbook: extra_oso_config.yml

- name: Additional Docker registry configuration
  import_playbook: registry_config.yml

- name: Setup default www app
  import_playbook: setup_default_www_app.yml

- name: Setup InfluxDB nodes
  import_playbook: setup_influxdb_nodes.yml

- name: Deploy monitoring
  import_playbook: deploy_monitoring.yml
  when: deploy_monitoring|default(false)|bool

- name: Deploy the namespace project label controller
  import_playbook: deploy_ns_project_label_webhook.yml
  when: deploy_ns_project_label_webhook|default(false)|bool

- name: Deploy app templates and related objects
  import_playbook: add_app_templates.yml
  when: add_app_templates|default(true)|bool

- name: Create poc service accounts
  import_playbook: create_poc_service_accounts.yml

- name: Deploy the registry image pruner
  import_playbook: deploy_image_pruner.yml

# Fix: make sure origin-master-controllers have up to date resolv.conf with local resolution
- name: Fix - restart master controllers
  import_playbook: fix_restart_master_controllers.yml

- name: Set service broker feature flags based on inventory
  hosts: all
  tasks:
    - set_fact:
        ansible_service_broker_install: "{{ inv_ansible_service_broker_install }}"
        template_service_broker_install: "{{ inv_template_service_broker_install }}"
      when:
        - inv_ansible_service_broker_install is defined
        - inv_template_service_broker_install is defined
