---
- name: Do additional Docker registry configuration
  hosts: masters[0]
  tasks:
    - name: update Docker image used for the registry
      oc_edit:
        name: docker-registry
        namespace: default
        kind: dc
        content:
          spec.template.spec.containers[0].image: "{{ registry_docker_image }}"

    - name: get certificate for registry
      slurp:
        src: '/etc/origin/master/registry.crt'
      register: registry_cert_file

    - name: put registry certificate content into variable
      set_fact:
        registry_dest_cert: "{{ registry_cert_file['content'] | b64decode }}"

    - name: create a re-encrypt route with a proper cert for the registry
      oc_route:
        name: docker-registry-reencrypt
        namespace: default
        cert_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt"
        key_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.key"
        cacert_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}_ext_ca.crt"
        dest_cacert_content: "{{ registry_dest_cert }}"
        service_name: "docker-registry"
        port: "5000"
        host: "docker-registry.{{ openshift_public_hostname }}"
        tls_termination: "reencrypt"
      run_once: true

    - name: update registry URL in registry console
      oc_env:
        state: present
        name: registry-console
        namespace: default
        kind: dc
        env_vars:
          REGISTRY_HOST: docker-registry.{{ openshift_public_hostname }}
      run_once: true

    - name: check if we already have registry-console.cert created
      stat:
        path: /etc/origin/master/registry-console.cert
      register: registry_console_cert

    - name: create registry console cert file with a proper cert+key
      shell: >
        cat
        /etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt
        /etc/origin/master/named_certificates/{{ openshift_public_hostname }}.key
        > /etc/origin/master/registry-console.cert
      when: registry_console_cert.stat.exists == False or
            replace_registry_console_cert|default(False)|bool == True

    - name: set access rights for registry-console.cert
      file:
        path: /etc/origin/master/registry-console.cert
        owner: root
        group: root
        mode: 0640

    - name: create cert secret for registry console
      oc_secret:
        state: present
        namespace: default
        name: console-secret
        files:
          - name: registry-console.cert
            path: '/etc/origin/master/registry-console.cert'
      run_once: true

    - name: add cert secret as a volume to dc/registry-console
      oc_volume:
        state: present
        name: registry-console
        namespace: default
        kind: dc
        mount_type: secret
        secret_name: console-secret
        vol_name: console-secret-vol
        mount_path: /etc/cockpit/ws-certs.d
      run_once: true

    - name: redeploy registry console if needed
      command: oc rollout latest registry-console -n default
      when: replace_registry_console_cert|default(False)|bool == True

    # workaround to: https://github.com/kubernetes/kubernetes/issues/56348
    # temporary fix: https://github.com/kubernetes/kubernetes/issues/56348#issuecomment-382633909
    - name: check if registry console has an orphan finalizer
      shell: oc get route registry-console -n default -o=jsonpath='{.metadata.finalizers[0]}'
      register: registry_console_route_finalizer

    - name: remove orphan finalizer from registry console
      shell: oc patch route registry-console -n default --type=json -p='[{"op":"remove", "path":"/metadata/finalizers/0"}]'
      when: registry_console_route_finalizer.stdout == "orphan"

    - name: modify route to registry console to be in the API domain
      oc_route:
        state: present
        name: registry-console
        namespace: default
        service_name: registry-console
        tls_termination: passthrough
        host: registry-console.{{ openshift_public_hostname }}

    - name: add redirect rule for insecure URL to registry console route
      oc_edit:
        kind: routes
        name: registry-console
        namespace: default
        content:
          spec.tls.insecureEdgeTerminationPolicy: Redirect

    - name: modify OAuthClient config for the registry console
      shell: >
        oc get oauthclient
        cockpit-oauth-client -o json |
        jq '.redirectURIs[0] |=
        "https://registry-console.{{ openshift_public_hostname }}"' |
        oc replace -f -

    - name: check if registry PVC exists
      shell: oc get pvc -n default registry
      register: existing_registry_pv
      changed_when: false
      failed_when: false

    - name: create and attach a persistent volume for registry
      shell: >
        oc set volume -n default dc/docker-registry --add
        --mount-path=/registry --overwrite
        --name=registry-storage
        --claim-name=registry
        -t pvc --claim-size={{ registry_claim_size|default('200Gi') }}
      when:
        - existing_registry_pv.stdout_lines | length == 0
        - skip_pvc|default(false) == false

    - name: attach the existing persistent volume for registry
      shell: >
        oc set volume -n default dc/docker-registry --add
        --mount-path=/registry --overwrite
        --name=registry-storage --claim-name=registry
      when:
        - existing_registry_pv.stdout_lines | length > 0
        - skip_pvc|default(false) == false

    - name: Deploy registry-console on infra nodes by adding a node selector
      oc_edit:
        namespace: default
        kind: deploymentconfig
        name: registry-console
        content:
          spec.template.spec.nodeSelector.type: master
