---
- name: Remove nodes from the cluster
  hosts: masters[0]
  tasks:
    - name: get list of nodes
      shell: oc get nodes -o name | cut -d'/' -f2 | xargs
      register: current_nodes

    - name: put current nodes in a list
      set_fact:
        current_nodes_list: "{{ current_nodes.stdout.split(' ') }}"

    - name: create a list of nodes to drain
      set_fact:
        nodes_to_drain: "{{ current_nodes_list | intersect(nodes_to_remove) }}"

    - name: drain nodes
      command: oc adm drain {{ item }} {{ (delete_local_data|d()|bool == True) | ternary('--delete-local-data','') }}
      with_items: "{{ nodes_to_drain }}"

    - name: remove nodes that were drained
      command: oc delete node {{ item }}
      with_items: "{{ nodes_to_drain }}"

- name: Clear up generated configs
  hosts: masters
  tasks:
    - name: remove generated config dirs
      file:
        path: /etc/origin/generated-configs/node-{{ item }}
        state: absent
      with_items: "{{ nodes_to_remove }}"

    - name: remove generated config archives
      file:
        path: /etc/origin/generated-configs/node-{{ item }}.tgz
        state: absent
      with_items: "{{ nodes_to_remove }}"

- name: Clean up /etc/hosts in the cluster
  hosts: all
  become: yes
  tasks:
    - name: remove outdated lines in /etc/hosts
      lineinfile:
        state: absent
        dest: /etc/hosts
        regexp: "^.*{{ item }}.*$"
      with_items: "{{ nodes_to_remove }}"

- name: Update Heat stacks to remove nodes
  import_playbook: provision.yml
