---

- import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/openshift-etcd/scaleup.yml"
  when:
    - groups['new_etcd']|default([])

- import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/openshift-master/scaleup.yml"
  when:
    - groups['new_masters']|default([])

# we can only run node scaleup playbook when no masters are being present in new_nodes
- import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/openshift-node/scaleup.yml"
  when:
    - groups['new_nodes']|default([])
    - not groups['new_masters']|default([])
