- name: Setup default www app
  hosts: masters[0]
  tasks:
    # block for conditionally deploying default-www-app
    - block:
      - name: create project default-www
        oc_project:
          state: present
          name: default-www
          display_name: "The default OpenShift web application"

      - name: check if app has been deployed
        shell: oc get dc -n default-www default-www-app
        register: existing_default_www_app
        changed_when: false
        failed_when: false

      - name: create app
        shell: oc new-app -n default-www --name default-www-app {{ default_www_app_repo }}
        when: existing_default_www_app.stdout_lines | length == 0

      # TODO: use oc_env when that works (at the time of this writing it does not)
      - name: set environment variables
        shell: oc set env -n default-www dc/default-www-app {{ item.key }}="{{ item.value }}"
        with_dict: "{{ default_www_app_environment }}"

      - name: create default www app routes
        oc_route:
          state: present
          name: "default-www-{{ item.name }}"
          namespace: default-www
          service_name: default-www-app
          cert_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt"
          key_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.key"
          cacert_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}_ext_ca.crt"
          host: "{{ item.hostname|default(item.name + '.' + openshift_public_hostname) }}"
          tls_termination: edge
        with_items:
        - name: default
          hostname: "{{ openshift_public_hostname }}"
        - name: www
        - name: admin

      - name: add redirect rule to default www app routes
        oc_edit:
          kind: routes
          name: "default-www-{{ item }}"
          namespace: default-www
          content:
            spec.tls.insecureEdgeTerminationPolicy: Redirect
        with_items:
        - default
        - www
        - admin

      - name: wait for app to start responding
        uri:
          url: https://{{ openshift_public_hostname }}
          method: GET
        register: app_response
        until: app_response.status == 200
        retries: 120

      when:
      - deploy_default_www_app | default(false) | bool
