---
- name: Fork public image to be used as base image for VMs if needed
  import_playbook: fork_public_image.yml

- name: Provision resources for OpenShift using Heat
  import_playbook: provision.yml

- name: Prepare hosts for OpenShift installation
  import_playbook: pre_install.yml

- name: Install OpenShift
  import_playbook: install_3.9.yml

- name: Do post installation steps for OpenShift
  import_playbook: post_install.yml

# These need a working storage class in place, so install only after the
# post-install phase.
- name: Install service brokers
  import_playbook: "{{ os_ansible_path|default('../../openshift-ansible') }}/playbooks/openshift-service-catalog/config.yml"
  when:
    - ansible_service_broker_install or template_service_broker_install
    - groups['new_masters']|default([])|length == groups['masters']|default([])|length
