- name: limit the number of namespaces per user
  yedit:
    src: "{{ openshift_master_config_file }}"
    key: admissionConfig.pluginConfig.ProjectRequestLimit.configuration
    value: |
      apiVersion: v1
      kind: ProjectRequestLimitConfig
      limits:
      - maxProjects: "{{ default_max_namespaces_per_user }}"
      - selector:
          namespace_quota: unlimited
  notify:
    - restart master
    - restart master api
