---

# This playbook can be used to sync the number of volumes in Gluster and Heketi even when gluster is not responding.

- name: Get the list of Heketi volumes
  hosts: masters
  run_once: true
  tasks:

    - name: Get heketi volumes
      shell: oc rsh -n glusterfs deploymentconfig.apps.openshift.io/heketi-storage heketi-cli volume list | awk '{print $3}' | awk -F ':' '{print $2}'
      delegate_to: "{{ ansible_play_hosts | first }}"
      register: heketi_volume_list

    - name: Show heketi volumes
      debug:
        var: heketi_volume_list

    - name: scale down the heketi pods to 0
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
            name: heketi-storage
            namespace: glusterfs
          spec:
            replicas: 0
      when: not noop|default(True)

- name: Delete orphan gluster volumes
  hosts: glusterfs
  gather_facts: true
  become: true
  vars:
    - heketi_volume_list: "{{ hostvars[groups['masters'][0]].heketi_volume_list.stdout_lines }}"
  tasks:

    - name: set the gluster CLI command (native)
      set_fact:
        gluster_shell: "docker exec {{ gluster_container_id.stdout }}"
      when: openshift_storage_glusterfs_is_native

    - name: set the gluster CLI command (non-native)
      set_fact:
        gluster_shell: ""
      when: not openshift_storage_glusterfs_is_native

    - name: Get all the existing gluster volumes
      shell: "{{ gluster_shell }} ls -1 /var/lib/glusterd/vols"
      register: gluster_volume_ids

    - name: Assert that gluster_volume_ids is not empty
      assert:
        that:
          - gluster_volume_ids.stdout_lines | length > 0

    - name: Show the number of orphan volumes in gluster nodes
      debug:
        var: (gluster_volume_ids.stdout_lines | length) - (heketi_volume_list | length)

    - name: Show the list of gluster volumes to clean
      debug:
        var: item
      with_items:
        - "{{ gluster_volume_ids.stdout_lines }}"
      when:
        - item not in heketi_volume_list

    - name: Stop gluster
      service:
        name: glusterd
        state: stopped
      when: not noop|default(True)

    - name: Create backup directory
      file:
        name: "/var/gluster_recovery/glusterbackup_{{ansible_date_time.iso8601_basic_short}}"
        state: directory
      register: backup_directory
      when: not noop|default(True)

    - name: Move volumes to backup directory
      shell: "mv /var/lib/glusterd/vols/{{ item }} {{ backup_directory.path }}"
      with_items:
        - "{{ gluster_volume_ids.stdout_lines }}"
      when:
        - item not in heketi_volume_list
        - not noop|default(True)

    - name: Start Gluster
      service:
        name: glusterd
        state: started
      when: not noop|default(True)


- name: Scale Heketi back up
  hosts: masters
  run_once: true
  tasks:
    - name: Scale up the heketi pod to 1
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
            name: heketi-storage
            namespace: glusterfs
          spec:
            replicas: 1
      when: not noop|default(True)