---

- name: Update app domain certs
  hosts: "{{ groups.masters.0 }}"
  run_once: true
  
  tasks:
    - name:  Set certificate source
      set_fact:
        cert_source: "{{ app_domain_cert | default(api_domain_cert) }}"

    - name: Delete old secret
      oc_secret:
        state: absent
        namespace: default
        name: router-certs

    - name: Creating the new secret
      oc_secret:
        state: present
        namespace: default
        name: router-certs
        contents:
          - path: tls.key
            data: "{{ cert_source.tls_secret_key }}"
          - path: tls.crt
            data: "{{ (cert_source.tls_certificate + cert_source.tls_secret_key) }}"

