---

- name: Create temporary files on a RAM disk for TLS certs, ssh keys, OpenStack credentials
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - poc_facts
    - poc_deployer


- name: Create OpenShift certificates for master hosts
  hosts: masters
  roles:
  - role: openshift_master_facts
  - role: openshift_named_certificates


# CA info needs to be updated in the kubeconfigs
- name: Copy the new certificates, restart the master API, controllers and kubelet one master node at a time
  hosts: masters
  serial: 1
  vars:
    openshift_master_config_dir: "/etc/origin/master"
    openshift_node_config_dir: "/etc/origin/node"

  tasks:
    - name: update admin client kubeconfig CA data
      kubeclient_ca:
        client_path: "{{ openshift_master_config_dir }}/admin.kubeconfig"
        ca_path: "/etc/origin/master/named_certificates/{{ openshift_public_hostname }}.crt"

    - name: copy the admin client config(s)
      copy:
        src: "{{ openshift_master_config_dir }}/admin.kubeconfig"
        dest: "{{ item }}/.kube/config"
        remote_src: yes
        mode: 0700
        owner: "{{ item | basename }}"
        group: "{{ item | basename }}"
      with_items:
        - /root
        - /home/cloud-user

    - name: copy admin.kubeconfig in order to bootstrap the master node kubelet with fresh certificates
      copy:
        src: "{{ openshift_master_config_dir }}/admin.kubeconfig"
        dest: "{{ openshift_node_config_dir }}/{{ item }}"
        remote_src: true
      with_items:
        - "node.kubeconfig"
        - "bootstrap.kubeconfig"

    - name: restart master API and controllers
      command: /usr/local/bin/master-restart "{{ item }}"
      with_items:
        - api
        - controllers

    - name: restart origin-node and docker
      systemd:
        state: restarted
        name: "{{ item }}"
      with_items:
        - origin-node
        - docker

# CA info needs to be updated in bootstrap configs of the nodes 
- name: Fix bootstrap config for other nodes
  hosts: ssd,lb,glusterfs,influxdb
  serial: 1
  vars:
    openshift_master_config_dir: "/etc/origin/master"
    openshift_node_config_dir: "/etc/origin/node"

  tasks:
    - name: Copy TLS certificate for {{ item.domain }}
      copy:
        dest: "/tmp/{{ api_domain_cert.domain }}.crt"
        content: "{{ api_domain_cert.tls_certificate }}"
        mode: 0600
      
    - name: update admin client kubeconfig CA data
      kubeclient_ca:
        client_path: "{{ openshift_node_config_dir }}/bootstrap.kubeconfig"
        ca_path: "/tmp/{{ api_domain_cert.domain }}.crt"

    - name: update admin client kubeconfig CA data
      kubeclient_ca:
        client_path: "{{ openshift_node_config_dir }}/node.kubeconfig"
        ca_path: "/tmp/{{ api_domain_cert.domain }}.crt"

    - name: restart origin-node and docker
      systemd:
        state: restarted
        name: "{{ item }}"
      with_items:
        - origin-node
        - docker

